export interface Event {
    header: string,
    description: string,
    attendees: number,
    eventType: string,
    location: string,
    startDate: number | string,
    endDate: number | string,
    startTime: number | string,
    endTime: number | string,
    roleAccept: string[],
    image: string,
    eventId: number,
    clubName: string,
  }