export interface Time {
    eventHeader: String,
    description: String,
    attendees: number,
    eventType: String,
    location: String,
    startDate: number,
    endDate: number,
    startTime: number,
    endTime: number,
    roleAccept: String[],
    image: String,
    eventId: number,
    clubName: String,
  }